In [3]:

import pandas as pd
import matplotlib.pyplot as plt
from mpl_finance import candlestick_ochl
from matplotlib.pylab import date2num
import datetime
import talib
import stockdata as sd
import matplotlib.dates as mdates
# 获取贵州茅台从2018年元旦至2023年3月20日的行情数据start date ='2018-01-01end date =2023-03-20df = ts.get k data('600519',start=start date, end=end date)
# 计算MACD指标

df = sd.get_stock_price('000001')

df['EMA12'] = talib.EMA(df['close'], timeperiod=12)
df['EMA26'] = talib.EMA(df['close'], timeperiod=26)
df['DIF'] = df['EMA12'] - df['EMA26']
df['DEA'] = talib.EMA(df['DIF'], timeperiod=9)
df['MACD'] = 2 * (df['DIF'] - df['DEA'])
#画图展示
df['date'] = pd.to_datetime(df['date'])


df = df[df['date'] > '2015-01-01']
df

,Unnamed: 0,date,open,close,high,low,volumn,turnover,amp,percent_change,...,low_qfq,open_org,close_org,high_org,low_org,EMA12,EMA26,DIF,DEA,MACD
日期,,,,,,,,,,,,,,,,,,,,,
2015-01-05,1142,2015-01-05,9.79,9.81,9.99,9.52,2860436,4.565388e+09,4.29,1.14,...,9.52,15.99,16.02,16.28,15.60,9.150358,8.555475,0.594883,0.585864,0.018038
2015-01-06,1143,2015-01-06,9.69,9.65,10.07,9.49,2166421,3.453446e+09,5.24,-1.50,...,9.49,15.85,15.78,16.39,15.55,9.227226,8.636551,0.590675,0.586826,0.007697
2015-01-07,1144,2015-01-07,9.49,9.44,9.68,9.31,1700121,2.634796e+09,3.36,-1.90,...,9.31,15.56,15.48,15.83,15.30,9.259960,8.696066,0.563895,0.582240,-0.036690
2015-01-08,1145,2015-01-08,9.45,9.08,9.50,9.03,1407714,2.128003e+09,4.33,-3.36,...,9.03,15.50,14.96,15.57,14.90,9.232274,8.724505,0.507769,0.567346,-0.119154
2015-01-09,1146,2015-01-09,9.03,9.16,9.71,8.90,2508500,3.835378e+09,7.75,0.80,...,8.90,14.90,15.08,15.87,14.71,9.221155,8.756764,0.464391,0.546755,-0.164728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-06,61,2023-04-06,12.60,12.58,12.61,12.50,563321,7.064807e+08,0.87,-0.55,...,12.50,12.60,12.58,12.61,12.50,12.707371,12.984607,-0.277236,-0.302010,0.049548
2023-04-07,62,2023-04-07,12.57,12.62,12.69,12.50,607925,7.673548e+08,1.51,0.32,...,12.50,12.57,12.62,12.69,12.50,12.693929,12.957599,-0.263669,-0.294342,0.061344
2023-04-10,63,2023-04-10,12.64,12.68,12.70,12.58,640182,8.099431e+08,0.95,0.48,...,12.58,12.64,12.68,12.70,12.58,12.691786,12.937036,-0.245249,-0.284523,0.078547
2023-04-11,64,2023-04-11,12.70,12.54,12.72,12.52,777780,9.783029e+08,1.58,-1.10,...,12.52,12.70,12.54,12.72,12.52,12.668435,12.907626,-0.239191,-0.275457,0.072531
2023-04-12,65,2023-04-12,12.58,12.50,12.59,12.50,405435,5.079486e+08,0.72,-0.32,...,12.50,12.58,12.50,12.59,12.50,12.642522,12.877431,-0.234910,-0.267347,0.064875

In [ ]:
locator = mdates.AutoDateLocator()
formatter = mdates.DateFormatter('%Y-%m-%d')
df['date'] = df['date'].apply(date2num)
df_values = [tuple(vals) for vals in df[['date', 'open', 'close', 'high', 'low']].values]
fig, ax = plt.subplots(figsize=(20, 10))
candlestick_ochl(ax, df_values, width=0.6, colorup='red', colordown='green', alpha=0.8)
plt.plot(df['date'], df['DIF'], label='DIF')
plt.plot(df['date'], df['DEA'], label='DEA')
plt.bar(df['date'], df['MACD'], label='MACD', width=0.03 * len(df))
ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(formatter)
plt.legend()
plt.show()